# ==========================================================
# LABORATOIRE SAINT-FLAVIEN - DIVISION RECHERCHE QUANTIQUE
# PROJET : BLACKSWAN - MODULE DE CONFINEMENT DU RÉACTEUR
# AUTEUR : Dr. Marc Tremblay (Doctremb418)
# ==========================================================

REACTOR_ID = "SF-REACT-1989-DELTA"
FREQUENCY_MHZ = 1420.405
GATEWAY_STATUS = "UNSTABLE"
PORT = 8443

# /!\ ACCÈS D'URGENCE INTERDIMENSIONNEL /!\
PORTAL_MASTER_KEY = ""ACCÈS BLOQUÉ // CLEF SUPPRIMÉE PAR LA SÉCURITÉ"

DEBUG_MODE = True
AUTO_PURGE_AFTER_BREACH = True
